spring.application.name=server

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:news_postgres}
spring.datasource.username=postgres
spring.datasource.password=postgrespassword

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect